version: '3'

services:
    catalog:
        image: postgres:14.8
        environment:
            - POSTGRES_PASSWORD=testpassword

    irods-catalog-provider:
        build:
            context: ..
            dockerfile: ${dockerfile}
            args:
                - irods_package_version=${irods_package_version}
        depends_on:
            - catalog
        cap_add:
            - SYS_PTRACE
        security_opt:
            - seccomp=unconfined
        volumes:
            - shared_volume:/irods_testing_environment_mount_dir
            - /home/marflo/Documents/iRODS/irods:/irods_source:ro
            - /home/marflo/Documents/iRODS/irods_client_icommands:/icommands_source:ro
            - /home/marflo/Documents/iRODS/build-artifacts/ubuntu-20.04/externals:/externals:ro

    irods-catalog-consumer:
        build:
            context: ..
            dockerfile: ${dockerfile}
            args:
                - irods_package_version=${irods_package_version}
        depends_on:
            - irods-catalog-provider
        volumes:
            - shared_volume:/irods_testing_environment_mount_dir

# This volume is mounted on all test servers for detached mode testing which
# requires a common vault.
volumes:
    shared_volume:
